
var QuickSlideConfig;(function(config){var loadingSpinner=document.createElement("img"),popupImg,popupBox=document.createElement("div"),dimmer,sizeTimer,popupNext,popupPrev,popupCaption,normalizeEvent,addListener,delegateListener,triggerEvent,setupGalleryLinks,setPopup,recenterBox,showImage,hidePopup;normalizeEvent=function(e){if(!e.stopPropagation){e.stopPropagation=function(){this.cancelBubble=true;};e.preventDefault=function(){this.returnValue=false;};}
if(e.srcElement&&!e.target){e.target=e.srcElement;}
return e;};addListener=function(node,type,handler){var wrapHandler=function(e){handler.apply(node,[normalizeEvent(e||window.event)]);};if(node.attachEvent){node.attachEvent("on"+type,wrapHandler);}else{node.addEventListener(type,wrapHandler,false);}
return{node:node,type:type,handler:wrapHandler};};triggerEvent=function(node,type){var evt;if(document.createEventObject){evt=document.createEventObject();return node.fireEvent("on"+type,evt);}else{evt=document.createEvent("HTMLEvents");evt.initEvent(type,true,true);return!node.dispatchEvent(evt);}};setupGalleryLinks=function(){addListener(document.body,"click",function(e){var el=e.target,isQ;isQ=function(testEl){return testEl.nodeName.toUpperCase()==="A"&&testEl.getAttribute("rel").toUpperCase()==="QUICKSLIDE";};while(el&&!isQ(el)&&el!==this){el=el.parentNode;}
if(el&&isQ(el)){e.preventDefault();setPopup(el);}});};recenterBox=function(box,srcImg){var bs=box.style,cw,ch,scrollTop=document.body.scrollTop||(document.documentElement&&document.documentElement.scrollTop),px=0,py=0,w,h,cr,mw=config.max_width,mh=config.max_height;cw=window.innerWidth||document.documentElement.clientWidth;ch=window.innerHeight||document.documentElement.clientHeight;if(srcImg){w=srcImg.width;h=srcImg.height;if(mw&&w>mw){h=Math.round(h*mw/w);w=mw;srcImg.style.maxWidth=mw+"px";srcImg.style.maxHeight=h+"px";}
if(mh&&h>mh){w=Math.round(w*mh/h);h=mh;srcImg.style.maxHeight=mh+"px";srcImg.style.maxWidth=w+"px";}
if(config.show_caption){popupCaption.style.maxWidth=w+"px";}
px=box.offsetWidth-w;py=box.offsetHeight-h;if(config.auto_fit!==false){if(w+px>cw){h=Math.round(h*(cw-px)/w);w=cw-px;srcImg.style.maxWidth=w+"px";srcImg.style.maxHeight=h+"px";}
if(h+py>ch){w=Math.round(w*(ch-py)/h);h=ch-py;srcImg.style.maxHeight=h+"px";srcImg.style.maxWidth=w+"px";}}}else{cr=box.getBoundingClientRect();w=cr.right-cr.left;h=cr.bottom-cr.top;}
bs.top=(Math.round((ch-h)/2)+
(config.absolute_position?scrollTop:0)-
(py/2))+"px";bs.left=(Math.round((cw-w)/2)-px/2)+"px";};setPopup=function(fromNode){if(config.use_dimmer){document.body.appendChild(dimmer);}
document.body.appendChild(popupBox);popupBox.className="loading";recenterBox(popupBox);try{popupBox.removeChild(popupImg);}catch(err){}
popupImg=new Image();popupImg.id="quickslide-image";popupImg.style.display="none";addListener(popupImg,"error",function(err){if(!popupImg.width&&!popupImg.height){alert("There was a problem loading the image.\n\nThe server might have taken too long to respond, or the image might have been deleted.");hidePopup();}});if(config.show_caption){popupCaption.style.display="none";popupCaption.innerHTML=fromNode.getAttribute("title");}
popupImg.src=fromNode.getAttribute("href");sizeTimer=setInterval(function(){if(popupImg.width||popupImg.height){clearInterval(sizeTimer);showImage();}},100);};showImage=function(){popupBox.className="";popupImg.style.display="";if(config.show_caption){popupBox.insertBefore(popupImg,popupCaption);popupCaption.style.display="";}else{popupBox.appendChild(popupImg);}
recenterBox(popupBox,popupImg);};hidePopup=function(){clearInterval(sizeTimer);document.body.removeChild(popupBox);if(config.use_dimmer){document.body.removeChild(dimmer);}};config=config||{};popupBox.id="quickslide-popup-box";popupBox.style.position=config.absolute_position?"absolute":"fixed";popupBox.style.zIndex="9999";addListener(popupBox,"click",function(e){hidePopup();});if(config.use_dimmer){(function(){var ds;dimmer=document.createElement("div");ds=dimmer.style;ds.position="fixed";ds.zIndex="9998";ds.top="0";ds.right="0";ds.bottom="0";ds.left="0";dimmer.id="quickslide-dimmer";addListener(dimmer,"click",function(e){hidePopup();});}());}
if(config.show_caption){popupCaption=document.createElement("div");popupCaption.id="quickslide-caption";popupBox.appendChild(popupCaption);}
addListener(window,"load",function(){setupGalleryLinks();});}(QuickSlideConfig));